version: '3'

services:
  database:
   image: 'postgres:latest'
   restart: always
   
   ports: 
    - 5432:5432
   volumes: 
    - pgdata:/var/lib/postgresql/data
   
   environment:
    POSTGRES_USER: movie
    POSTGRES_PASSWORD: movie
    POSTGRES_DB: default_database
   
volumes:
  pgdata:  
    